In [3]:
import os
from skimage import data, io, segmentation, color, data
from skimage.transform import resize
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
#This sorts a given list into alphanumeric order
import re
def sorted_nicely(l):
    """ Sorts the given iterable in the way that is expected.
    Required arguments:
    l -- The iterable to be sorted.
    """
    convert = lambda text: int(text) if text.isdigit() else text
    alphanum_key = lambda key: [convert(c) for c in re.split('([0-9]+)', key)]
    return sorted(l, key = alphanum_key)

In [5]:
#This block will get the classification folder names and sort them into alphanumeric so it can be used later on for making classes.
current_directory = os.getcwd()
#print(current_directory)
classification_file_directory = current_directory + "/Classification_files"
classification_files_names = os.listdir(classification_file_directory)

for i in classification_files_names:
    if "." in i:
        classification_files_names.remove(i)

In [6]:
#This block will now take those file directories and find the underlying picture files
image_dictionary = {}
for folder_name in classification_files_names:
    individual_image_files = classification_file_directory + "/{}/face".format(folder_name)
    list_of_individual_images = os.listdir(individual_image_files)
    image_dictionary[folder_name] = sorted_nicely(list_of_individual_images)

#Now image_dictionary stores the key of the folder with the list of values in the folder
#I did this so that we can iterate through it easily.

In [7]:
#Now we should set up a class with attributes that we will need in order to classify
class Person:
    name_of_person = None
    list_of_vector_array = []
    gender = None
    race = None
    target = None

    def __init__(self, name, list_of_vector_array):
        self.name_of_person = name
        self.list_of_vector_array = np.array(list_of_vector_array)

In [8]:
#An example of using this could be
alphabetical_keys = sorted_nicely(list(image_dictionary))
temporary_list_for_class_use_later = []

for key in alphabetical_keys:

    image_list = []
    for i in image_dictionary[key]:
        vector_image = io.imread(classification_file_directory + "/{}/face/".format(key) + i)
        img_resized = resize(vector_image, (112, 92, 4))
        flatten_img = img_resized.flatten()
        image_list.append(flatten_img)

    person = Person(key, image_list)
    temporary_list_for_class_use_later.append(person)
#So Imread is the skimage thing we will be using to read the images. This cell is just a demonstration on how to use the key values in the dictionary made
#This makes it so that we can read all the images easily
#Note you should run the file in your own IDE because the CWD will change and it won't be Jason Tang

In [9]:
#Adding gender and race each person class

temporary_list_for_class_use_later[0].gender = "Male"
temporary_list_for_class_use_later[0].race = "Caucasian"

temporary_list_for_class_use_later[1].gender = "Male"
temporary_list_for_class_use_later[1].race = "Caucasian"

temporary_list_for_class_use_later[2].gender = "Male"
temporary_list_for_class_use_later[2].race = "Caucasian"

temporary_list_for_class_use_later[3].gender = "Male"
temporary_list_for_class_use_later[3].race = "Not Caucasian"

temporary_list_for_class_use_later[4].gender = "Male"
temporary_list_for_class_use_later[4].race = "Caucasian"

temporary_list_for_class_use_later[5].gender = "Male"
temporary_list_for_class_use_later[5].race = "Caucasian"

temporary_list_for_class_use_later[6].gender = "Female"
temporary_list_for_class_use_later[6].race = "Caucasian"

temporary_list_for_class_use_later[7].gender = "Female"
temporary_list_for_class_use_later[7].race = "Caucasian"

temporary_list_for_class_use_later[8].gender = "Female"
temporary_list_for_class_use_later[8].race = "Caucasian"

temporary_list_for_class_use_later[9].gender = "Male"
temporary_list_for_class_use_later[9].race = "Not Caucasian"

temporary_list_for_class_use_later[10].gender = "Male"
temporary_list_for_class_use_later[10].race = "Not Caucasian"

temporary_list_for_class_use_later[11].gender = "Male"
temporary_list_for_class_use_later[11].race = "Not Caucasian"

temporary_list_for_class_use_later[12].gender = "Male"
temporary_list_for_class_use_later[12].race = "Caucasian"

temporary_list_for_class_use_later[13].gender = "Male"
temporary_list_for_class_use_later[13].race = "Caucasian"

temporary_list_for_class_use_later[14].gender = "Male"
temporary_list_for_class_use_later[14].race = "Caucasian"

temporary_list_for_class_use_later[15].gender = "Male"
temporary_list_for_class_use_later[15].race = "Caucasian"

temporary_list_for_class_use_later[16].gender = "Male"
temporary_list_for_class_use_later[16].race = "Caucasian"

temporary_list_for_class_use_later[17].gender = "Male"
temporary_list_for_class_use_later[17].race = "Caucasian"

temporary_list_for_class_use_later[18].gender = "Male"
temporary_list_for_class_use_later[18].race = "Caucasian"

temporary_list_for_class_use_later[19].gender = "Female"
temporary_list_for_class_use_later[19].race = "Caucasian"

for i in temporary_list_for_class_use_later:
    if i.race == "Caucasian" and i.gender == "Male":
        i.target = 0
    elif i.race == "Caucasian" and i.gender == "Female":
        i.target = 1
    elif i.race == "Not Caucasian" and i.gender == "Male":
        i.target = 2
    elif i.race == "Not Caucasian" and i.gender == "Female":
        i.target = 3


In [10]:
Categories =["Male Cauc", "Female Cauc", "Male Not Cauc", "Female Not Cauc"]
vector_array = []
target_arr = []
print(temporary_list_for_class_use_later[0].list_of_vector_array)
for i in temporary_list_for_class_use_later:
    for j in i.list_of_vector_array:
        vector_array.append(j)
        target_arr.append(i.target)

flat_data = np.array(vector_array)
target=np.array(target_arr)

[[0.90980392 0.90980392 0.90980392 ... 0.52941176 0.52941176 0.52941176]
 [0.91372549 0.91372549 0.91372549 ... 0.53333333 0.53333333 0.53333333]
 [0.91372549 0.91372549 0.91372549 ... 0.56470588 0.56470588 0.56470588]
 ...
 [0.92156863 0.92156863 0.92156863 ... 0.75294118 0.75294118 0.75294118]
 [0.89803922 0.89803922 0.89803922 ... 0.72156863 0.72156863 0.72156863]
 [0.91372549 0.91372549 0.91372549 ... 0.83921569 0.83921569 0.83921569]]


In [11]:
df=pd.DataFrame(flat_data) #dataframe
df['Target']=target
x=df.iloc[:,:-1] #feature array
y=df.iloc[:,-1] #label data y = df['Target']
display(df)

0         1         2         3         4         5         6  \
0    0.909804  0.909804  0.909804  0.909804  0.913725  0.913725  0.913725   
1    0.913725  0.913725  0.913725  0.913725  0.913725  0.913725  0.913725   
2    0.913725  0.913725  0.913725  0.913725  0.913725  0.913725  0.913725   
3    0.913725  0.913725  0.913725  0.913725  0.913725  0.913725  0.913725   
4    0.913725  0.913725  0.913725  0.913725  0.913725  0.913725  0.913725   
..        ...       ...       ...       ...       ...       ...       ...   
570  0.160784  0.160784  0.160784  0.160784  0.149020  0.149020  0.149020   
571  0.156863  0.156863  0.156863  0.156863  0.164706  0.164706  0.164706   
572  0.149020  0.149020  0.149020  0.149020  0.164706  0.164706  0.164706   
573  0.188235  0.188235  0.188235  0.188235  0.188235  0.188235  0.188235   
574  0.054902  0.054902  0.054902  0.054902  0.105882  0.105882  0.105882   

            7         8         9  ...     41207     41208     41209  \
0    0.913725  0.913725  0.913725  ...  0.549020  0.545098  0.545098   
1    0.913725  0.913725  0.913725  ...  0.537255  0.533333  0.533333   
2    0.913725  0.913725  0.913725  ...  0.576471  0.564706  0.564706   
3    0.913725  0.913725  0.913725  ...  0.560784  0.552941  0.552941   
4    0.913725  0.913725  0.913725  ...  0.584314  0.576471  0.576471   
..        ...       ...       ...  ...       ...       ...       ...   
570  0.149020  0.164706  0.164706  ...  0.443137  0.439216  0.439216   
571  0.164706  0.160784  0.160784  ...  0.439216  0.443137  0.443137   
572  0.164706  0.164706  0.164706  ...  0.439216  0.443137  0.443137   
573  0.188235  0.172549  0.172549  ...  0.447059  0.443137  0.443137   
574  0.105882  0.062745  0.062745  ...  0.411765  0.337255  0.337255   

        41210     41211     41212     41213     41214     41215  Target  
0    0.545098  0.545098  0.529412  0.529412  0.529412  0.529412       0  
1    0.533333  0.533333  0.533333  0.533333  0.533333  0.533333       0  
2    0.564706  0.564706  0.564706  0.564706  0.564706  0.564706       0  
3    0.552941  0.552941  0.556863  0.556863  0.556863  0.556863       0  
4    0.576471  0.576471  0.576471  0.576471  0.576471  0.576471       0  
..        ...       ...       ...       ...       ...       ...     ...  
570  0.439216  0.439216  0.439216  0.439216  0.439216  0.439216       1  
571  0.443137  0.443137  0.443137  0.443137  0.443137  0.443137       1  
572  0.443137  0.443137  0.439216  0.439216  0.439216  0.439216       1  
573  0.443137  0.443137  0.447059  0.447059  0.447059  0.447059       1  
574  0.337255  0.337255  0.333333  0.333333  0.333333  0.333333       1  

[575 rows x 41217 columns]

In [12]:
%store x
%store y

Stored 'x' (DataFrame)
Stored 'y' (Series)
